Main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = "Main"

urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.about, name="about"),
    path("perfil", views.perfil, name="perfil"),
    path("editar-perfil", views.editar_perfil, name="editar_perfil"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Proyecto1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Main.urls")),
    path("blog/", include("blog.urls")),
]

blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    # path("post/list", views.post_list, name="post_list"),
    path("post/list", views.PostListView.as_view(), name="post_list"),
    # path("post/create", views.post_create, name="post_create"),
    path("post/create", views.PostCreateView.as_view(), name="post_create"),
    path("post/update/<int:pk>/", views.PostUpdateView.as_view(), name="post_update"),
    path("post/detail/<int:pk>/", views.PostDetailView.as_view(), name="post_detail"),
    path("post/delete/<int:pk>/", views.PostDeleteView.as_view(), name="post_delete"),
]

Main/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Avatar(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='avatares', null=True, blank=True)

    def __str__(self):
        return f"{self.user} - {self.imagen}"

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    class Estado(models.TextChoices):
        BORRADOR = 'B', 'Borrador'
        PUBLICADO = 'P', 'Publicado'
    titulo = models.CharField(max_length=100)
    contenido = models.TextField()
    fecha_publicacion = models.DateTimeField(auto_now_add=True)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    estado = models.CharField(max_length=1, choices=Estado.choices, default=Estado.BORRADOR)
    
    def __str__(self):
        return self.titulo

Main/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User

from .models import Avatar

class EditUserForm(UserChangeForm):
    email = forms.EmailField(required=True, label='Email')
    first_name = forms.CharField(required=True, label='Nombre')
    last_name = forms.CharField(required=True, label='Apellido')
    
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'password')

class AvatarForm(forms.ModelForm):
    class Meta:
        model = Avatar
        fields = ['imagen']

blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["titulo", "contenido", "estado"]

Main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .forms import EditUserForm, AvatarForm
from .models import Avatar

# Create your views here.
def index(request):
    return render(request, 'Main/index.html')

def about(request):
    return render(request, 'Main/about.html')

def perfil(request):
    return render(request, 'Main/perfil.html')

@login_required
def editar_perfil(request):
    if request.method == "POST":
        form = EditUserForm(request.POST, instance=request.user)
        
        #VERIFICAR SI EL USUARIO YA TIENE UN AVATAR
        try:
            avatar = request.user.avatar
        except Avatar.DoesNotExist:
            avatar = None
        
        #CREAR EL FORMULARIO DE AVATAR SEGUN SI EL USUARIO TIENE UNO O NO
        if avatar:
            avatar_form = AvatarForm(request.POST, request.FILES, instance=avatar)
        else:
            avatar_form = AvatarForm(request.POST, request.FILES)
        
        if form.is_valid() and avatar_form.is_valid():
            form.save()
            avatar_instance = avatar_form.save(commit=False)
            avatar_instance.user = request.user #ASIGNAR EL USUARIO ACTUAL AL AVATAR
            avatar_instance.save()
            return redirect("Main:perfil")
    else:
        form = EditUserForm(instance=request.user)
        if hasattr(request.user, "avatar"):
            avatar_form = AvatarForm(instance=request.user.avatar)
        else:
            avatar_form = AvatarForm()
    # Renderizar el formulario de edición de perfil y el formulario de avatar
    return render(request, "Main/editar_perfil.html", {"form": form, "avatar_form": avatar_form})

blog/views.py
from django.shortcuts import render, redirect
from .models import Post
from django.urls import reverse_lazy
from .forms import PostForm
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView

# Create your views here.

#funcion normal para lista de posts
def post_list(request):
    busqueda = request.GET.get("busqueda", None)
    if busqueda:
        post_list = Post.objects.filter(titulo__icontains=busqueda)
    else:
        post_list = Post.objects.all()
    return render(request, 'blog/post_list.html', context={"posts": post_list})

#clase basada en vista para el listado de posts
class PostListView(ListView):
    model = Post
    templñate_name = 'blog/post_list.html'
    context_object_name = 'posts'
    
    def get_queryset(self):
        queryset = super().get_queryset()
        busqueda = self.request.GET.get("busqueda", None)
        if busqueda:
            queryset = queryset.filter(titulo__icontains=busqueda)
        return queryset

def post_create(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            if request.user.is_authenticated:
                post.autor = request.user
                post.save()
                return redirect("blog:post_list")
        else:
            form.add_error(None, "Debes estar logueado para crear una publicacion")
    else:
        form = PostForm()
    return render(request, 'blog/post_create.html', context={"form": form})

class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy("blog:post_list")
    
    def form_valid(self, form):
        if self.request.user.is_authenticated:
            form.instance.autor = self.request.user
        else:
            form.add_error(None, "Debes estar logueado para crear una publicacion")
            return self.form_invalid(form)
        return super().form_valid(form)

class PostUpdateView(UpdateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy("blog:post_list")

class PostDetailView(DetailView):
    model = Post

class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy("blog:post_list")

myapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context = {"mensaje": "Bienvenidos a mi aplicación Django"}
    return render(request, "myapp/index.html", context)

Main/templates/Main/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog | {% block title %} {% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Mi Sitio</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'Main:index' %}">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:post_list' %}">Blog</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Main:editar_perfil' %}">
                            {% if user.avatar.imagen %}
                            <img src="{{ user.avatar.imagen.url }}" alt="" class="rounded-circle" width="30"
                                height="30">
                            {% endif %} {{user.username}}
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <h1 class="text-center my-4">
            {% block content_title %}
            {% endblock content_title %}
        </h1>
        {% block content %}
        {% endblock content %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq"
        crossorigin="anonymous"></script>
</body>

</html>

Main/templates/Main/editar_perfil.html
{% extends 'Main/base.html' %}

{% block title %}
    Editar Perfil
{% endblock title %}

{% block content_title %}
    Editar Perfil
{% endblock content_title %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            {{ avatar_form.as_table }}
        </table>
        <button type="submit">Guardar Cambios</button>
    </form>
{% endblock content %}

Main/templates/Main/index.html
{% extends 'Main/base.html' %}

{% block title %}
    Inicio
{% endblock title %}

{% block content_title %}
    Blog sobre Python
{% endblock content_title %}

{% block content %}
    <button>
        <a href="{% url 'blog:post_list' %}">Ingresar</a>
    </button>
{% endblock content %}

Main/templates/Main/perfil.html
{% extends 'Main/base.html' %}

{% block title %}
    Perfil
{% endblock title %}

{% block content_title %}
    Perfil de {{ user.username }}
{% endblock content_title %}

{% block content %}
    <p>Nombre de usuario: {{ user.username }}</p>
    <p>Nombre: {{ user.first_name }}</p>
    <p>Apellido: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <a href="{% url 'Main:editar_perfil' %}">Editar Perfil</a>
{% endblock content %}

blog/templates/blog/blog_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de publicaciones</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Mi Sitio</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/blog/">Blog</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <h1 class="text-center my-4">Lista de Publicaciones</h1>
    <ul class="list-unstyled">
        {% for post in posts %}
        <li class="mb-4">
            <a href="#" class="text-decoration-none">
                <div class="card shadow-sm m-4">
                    <div class="card-body">
                        <h5 class="card-title text-primary">{{ post.titulo }}</h5>
                        <p class="card-text text-muted">{{ post.contenido }}</p>
                        <small class="text-secondary">Publicado el {{ post.fecha_publicacion }}</small>
                    </div>
                </div>
            </a>
        </li>
        {% endfor %}
    </ul>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq"
        crossorigin="anonymous"></script>
</body>

</html>

blog/templates/blog/post_confirm_delete.html
{% extends 'Main/base.html' %}

    {% block title %}
        Eliminar
    {% endblock title %}

    {% block content_title %}
        Eliminar una publicación
    {% endblock content_title %}

    {% block content %}
        <h2>¿Está seguro de que desea eliminar la publicación "{{ object }}"?</h2>
        <form method="post">
            {% csrf_token %}
            <input type="submit" value="Eliminar" class="btn btn-danger">
        </form>
        <a href="{% url 'blog:post_list' %}" class="btn btn-secondary">Cancelar</a>
    {% endblock content %}

blog/templates/blog/post_create.html
{% extends 'Main/base.html' %}

    {% block title %}
        Publicar
    {% endblock title %}

    {% block content_title %}
        Formulario para crear una publicación
    {% endblock content_title %}

    {% block content %}
        <form method="post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value="Enviar" class="btn btn-primary">
            <a href="{ url 'blog:post_list' }"></a>
        </form>
    {% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'Main/base.html' %}

    {% block title %}
        Detalle
    {% endblock title %}

    {% block content_title %}
        Vista en detalle de una publicación
    {% endblock content_title %}

    {% block content %}
        <ul>
            <li>Titulo: {{ object.titulo }}</li>
            <li>Autor: {{ object.autor }}</li>
            <li>Contenido: {{ object.contenido }}</li>
            <li>Fecha de publicación: {{ object.fecha_publicacion }}</li>
            <li>Estado: {{ object.estado }}</li>
        </ul>
        <div>
            <a href="{% url 'blog:post_list' %}">Volver</a>
        </div>
    {% endblock content %}

blog/templates/blog/post_form.html
{% extends 'Main/base.html' %}

    {% block title %}
        Publicar
    {% endblock title %}

    {% block content_title %}
        {% if form.instance.pk %}
            Formulario para crear una publicación
        {% else %}
            Formulario para editar una publicación
        {% endif %}
    {% endblock content_title %}

    {% block content %}
        <form method="post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value="Enviar" class="btn btn-primary">
            <a href="{ url 'blog:post_list' }"></a>
        </form>
    {% endblock content %}

blog/templates/blog/post_list.html
{% extends 'Main/base.html' %}

    {% block title %}
        Publicaciones
    {% endblock title %}

    {% block content_title %}
    Lista de Publicaciones
    {% endblock content_title %}

    {% block content %}
    <a href="{% url 'blog:post_create' %}" class="btn btn-primary mb-3">Crear Publicación</a>

    <form action="{% url 'blog:post_list' %}" method="get">
        <input type="text" name="busqueda" placeholder="Buscar..." class="form-control mb-3" type="submit">
    </form>

    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>Título</th>
                    <th>Autor</th>
                    <th>Fecha de Creación</th>
                    <th>Estado</th>
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                    <tr>
                        <td>{{ post.titulo }}</td>
                        <td>{{ post.autor }}</td>
                        <td>{{ post.fecha_publicacion }}</td>
                        {% if post.estado == "B" %}
                            <td>Borrador</td>
                        {% else %}
                            <td><strong>Publicado</strong></td>
                        {% endif %}
                        <td class="text-center">
                            <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-info">Ver Mas</a>
                            <a href="{% url 'blog:post_update' post.id %}" class="btn btn-warning">Editar</a>
                            <a href="{% url 'blog:post_delete' post.id %}" class="btn btn-danger">Eliminar</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endblock content %}

myapp/templates/myapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Django App</title>
</head>
<body>
    <h1>Hola Django!</h1>
    <p>{{ mensaje }}</p>
</body>
</html>